### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by flamed0g** [atmaranto/ComfyUI-SaveAsScript#1]
Hi there!

I am absolutely loving this fork and the whole idea of all the extra features you've added. I was wondering if I could perhaps add you to Discord and ask a few questions.

I would really appreciate it.

Thanks a lot and keep up the great work! 🔥

**Comment by atmaranto** [comment]
Hi! Thanks for your interest. I'm afraid I don't give out y Discord publicly, but I'd be glad to answer any questions you have here in Issues. That way, others with the same questions can see their answers too.

**Comment by flamed0g** [comment]
> Hi! Thanks for your interest. I'm afraid I don't give out y Discord publicly, but I'd be glad to answer any questions you have here in Issues. That way, others with the same questions can see their answers too.

Ah I see! That makes sense actually. Basically I was wondering if it is possible to run a specific workflow without booting ComfyUI at all or if there are any other posibilities here.

I tried out your fork and I had a few issues here and there that I wasn't able to fix just yet, but I also noticed that it does boot up ComfyUI. First I thought this just exported to native Python code and wouldn't need ComfyUI at all or atleast on it's own, standalone.

Maybe this is not possible at all but fairly new here, so yeah not quite sure.

**Comment by atmaranto** [comment]
While it would _theoretically_ be possible to run the code without booting up ComfyUI, it probably wouldn't be realistic. Support for custom nodes especially relies on the fact that we simulate the ComfyUI server and its execution environment. We can't predict what aspects of the ComfyUI server custom nodes will rely upon.

We could make a framework that would mimic a lot of the features of the ComfyUI server, but at that point, we're just reimplementing ComfyUI. That code was implemented by the original maintainer, but I don't _believe_ the server should actually be listening for requests. It's just there for the API.
