### ISSUE TITLE
Script doesn't work with newest version of ComfyUI

### ISSUE THREAD

**Issue by Goktug** [atmaranto/ComfyUI-SaveAsScript#7]
Hey,

In the new version of ComfyUI, they replaced `import_custom_nodes` method with `init_builtin_extra_nodes`, `init_external_custom_nodes` ([Commit](https://github.com/comfyanonymous/ComfyUI/commit/9dd549e253f0e2c5e6360f9349b0872af18d8962))

https://github.com/atmaranto/ComfyUI-SaveAsScript/blob/be237bd10ac2d749c1b52592c3fa1547f79582eb/comfyui_to_python_utils.py#L17

Your script also requires the following change.

```
from nodes import init_builtin_extra_nodes, init_external_custom_nodes
```

Currently, when I run the script, I encounter the following error:

```
ImportError: cannot import name 'init_custom_nodes' from 'nodes' (/ComfyUI/nodes.py)
```

Could you please address this issue?

**Comment by menahem121** [comment]
please 😁

**Comment by atmaranto** [comment]
I've been a bit busy, but I'll work on fixing this today or tomorrow.

**Comment by szRush** [comment]
just modify init_custom_nodes to init_extra_nodes would be ok

**Comment by pydn** [comment]
@Goktug @menahem121 If you are still waiting on this, the update has been made in the original [repo](https://github.com/pydn/ComfyUI-to-Python-Extension).

**Comment by atmaranto** [comment]
Sorry; I took a bit of a lengthy hiatus. This should be resolved now.
